### ISSUE TITLE
Estável para produção?

### ISSUE THREAD

**Issue by Thyoity** [mazinsw/nfe-api#1]
Esta API, principalmente a parte NFe e NFCe (as que planejo usar) pode ser utilizada para produção?

EDITEI: Ah, pelo que dei uma olhada no código, a parte de NFe não está implementada ainda, certo?

**Comment by mazinsw** [comment]
Sim, a NFCe já está pronta e em produção em alguns clientes pelo Brasil, a NFe só não está pronto porque falta testar, se você se interessar posso lhe ajudar a implementar os dois modelos, assim aproveito para validar a NFe.

**Comment by Thyoity** [comment]
Minha empresa está desenvolvendo um ERP Cloud SAAS em Full Stack Javascript.

Precisamos de um Web Service que faça a emissão da NFe e NFCe para diferentes CNPJ's.
Entrei em contato com empresas que já fazem isso como serviço, ex: eNotas Gateway, mas achei muito caro, já que minha empresa segue um modelo de startup, onde o plano de assinatura para usar o ERP vai ser num preço bem acessível (o valor do serviço deles era quase superior ao que planejamos inicialmente para a assinatura do nosso ERP, e com um atendimento péssimo).

Estou procurando por alternativas mais em conta, e agora estou vendo se vale a pena desenvolver algo e manter nossa própria API, nosso servidor de emissão de NF-e e NFC-e. Foi aí que encontrei essa biblioteca.

O desenvolvimento do nosso sistema ainda não chegou na parte da emissão da nota, ainda vai um mês provavelmente. Porém estou pesquisando como trataremos esse assunto.

Não tenho experiência com emissão de notas fiscais (tenho outra pessoa na empresa que entende um pouco mais pois ele já emite notas fiscais de forma manual para outra empresa).

Já tenho o certificado (acredito que seja o A1).
Se você se prontificar a me ajudar, eu sabendo como funciona a emissão com essa lib, saberei depois me virar e montar o Web Service de que necessito para minha empresa.

Podemos conversar mais, tem algum contato? Skype, Hangouts, Whatsapp?

**Comment by mazinsw** [comment]
Estou disposto a ajudar tecnicamente na implantação da NFe para seu ERP, mas com algumas condições que podemos tratar por outro canal de comunicação, de fato os serviços existentes cobram muito caro, por isso desenvolvi essa solução aberta. Envia seu Skype para o E-mail que está na página do projeto na sessão Expansão do projeto, que iremos conversar melhor sobre esse assunto.

**Comment by Thyoity** [comment]
Enviei um e-mail com meu Skype.

**Comment by Greelings** [comment]
@mazinsw A parte NFCe ainda pode ser utilizada para produção? A versão atual (NFCe) suporta quais estados ?

**Comment by mazinsw** [comment]
Obrigado, irei criar a documentação e exemplo em breve

**Comment by marceloborth** [comment]
Boa... exemplos são muito importantes
