### ISSUE TITLE
Certificado digital A1 de homologação

### ISSUE THREAD

**Issue by Greelings** [mazinsw/nfe-api#2]
Bom dia, como posso gerar um certificado digital A1 de homologação para testes (emissão de notas fiscais NFC-e)? Obrigado.

**Comment by mazinsw** [comment]
O certificado digital A1 é gerado para um CNPJ por entidades autorizadas e permite o uso em homologação e produção, para emitir notas é necessário habilitar o uso de notas modelo 65 (NFC-e) ou 55 (NF-e) no site da Sefaz e nele mesmo gerar o CSC para o ambiente desejado
