### ISSUE TITLE
Falha no envio da nota

### ISSUE THREAD

**Issue by Greelings** [mazinsw/nfe-api#3]
Bom dia, 

A nota foi processada, recebi um arquivo XML mas também este erro:
`<xJust>Falha no envio da nota: SSL peer certificate or SSH remote key was not OK: SSL certificate problem: unable to get local issuer certificate</xJust>`

Não posso utilizar esta biblioteca com uma conexão HTTPS?
Obrigado.

**Comment by mazinsw** [comment]
Olá, essa biblioteca só funciona com HTTPS, mas para que funcione você precisa configurar seu PHP informando a cadeia de certificados dos servidores da SEFAZ, o arquivo cacert da curl deve ser informado no php.ini, em breve irei colocar essas configurações já nativa na biblioteca

**Comment by Greelings** [comment]
Muito obrigado pela resposta. Vou esperar a atualização.
