### ISSUE TITLE
Emissor não habilitado para emissão de NF-e

### ISSUE THREAD

**Issue by Greelings** [mazinsw/nfe-api#4]
Estou com esse erro : "Emissor não habilitado para emissão de NF-e"

A coisa estranha é que eu sou habilitado e que consigo emitir notas pelo programa "emissor de nota fiscal 4.0" da sabrae.

Será que no ambiente de homologação eu preciso colocar uma razão social específica, tipo :
"NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO – SEM VALOR FISCAL" ?

**Comment by mazinsw** [comment]
Acredito que esteja habilitado somente para ambiente de produção, ou talvez esteja emitindo uma NF-e em vez de NFC-e. Atualmente essa lib só foi testada para NFC-e, logo NF-e provavelmente não vai funcionar de primeira, talvez tenha que fazer algumas alterações

**Comment by Greelings** [comment]
Obrigado
