### ISSUE TITLE
Exemplo de como gerar a NFE ou NFCE

### ISSUE THREAD

**Issue by softcia** [mazinsw/nfe-api#7]
Boa Noite.

Voce tem algum exemplo de como preencher a NFE ou NFCE apartir de um banco de dados Mysql, eu estou montando uma
Tela para pedir os dados e gravar e apartir das Informações preencher os campos da NFE ou NFCE. 

Se tiver um exemplo de como fazer isso. Sou cru em PHP estou vindo do Delphi por necessidade de criar uma programa para gerar  NFCE em um Celular.
Ou se me passar quais .PHP devo alterar?
Voce sabe se tem o Campo cbenef?

Att.

Mario Moreira

**Comment by mazinsw** [comment]
Olá, possui sim, na pasta examples, lembrando que apenas NFC-e foi homologada nesse projeto, para a NF-e falta poucos ajustes que você mesmo pode fazer contribuindo para o projeto.
